import type { ManagedAppRegistry } from "@/mcp/app-registry"

export const manifest: ManagedAppRegistry.CatalogEntry = {
  id: "gmail",
  name: "Gmail",
  description: "Managed MCP app for Gmail operations under opencode runtime ownership.",
  version: "0.1.0",
  source: {
    type: "builtin",
    owner: "opencode",
    package: "@opencode-ai/gmail",
    entrypoint: "packages/opencode/src/mcp/apps/gmail",
    localOnly: true,
  },
  capabilities: [
    {
      id: "gmail.oauth",
      label: "Google account binding",
      kind: "oauth",
      description:
        "Binds the managed app to an explicitly authenticated Google account under canonical account ownership.",
      operations: ["read"],
    },
    {
      id: "gmail.labels.read",
      label: "Label discovery",
      kind: "tool",
      description: "Enumerates system and user labels with unread counts.",
      operations: ["list", "read"],
    },
    {
      id: "gmail.messages.read",
      label: "Message inspection",
      kind: "tool",
      description: "Searches, lists, and reads Gmail messages with full body decoding.",
      operations: ["list", "read", "query"],
    },
    {
      id: "gmail.messages.write",
      label: "Message composition",
      kind: "tool",
      description: "Sends new messages, replies to threads, and forwards messages.",
      operations: ["create"],
    },
    {
      id: "gmail.messages.manage",
      label: "Message management",
      kind: "tool",
      description: "Modifies labels on messages and moves messages to trash.",
      operations: ["update", "delete"],
    },
    {
      id: "gmail.drafts",
      label: "Draft management",
      kind: "tool",
      description: "Lists and creates email drafts.",
      operations: ["list", "create"],
    },
  ],
  permissions: [
    { id: "gmail.read", label: "Read emails, labels, and drafts", required: true },
    { id: "gmail.write", label: "Send, reply, forward, and manage emails", required: true },
  ],
  requiredConfig: ["googleOAuth"],
  auth: {
    providerKey: "gmail",
    ownership: "canonical-account",
    type: "oauth",
    required: true,
    allowImplicitActiveAccount: false,
    scopes: ["https://mail.google.com/"],
  },
  configContract: {
    fields: [{ key: "googleOAuth", label: "Google OAuth client", required: true, secret: true }],
  },
  toolContract: {
    namespace: "gmail",
    tools: [
      {
        id: "list-labels",
        label: "List labels",
        capabilityId: "gmail.labels.read",
        description: "Return all Gmail labels (system and user) with unread counts.",
        mutates: false,
        requiresConfirmation: false,
        arguments: [],
      },
      {
        id: "list-messages",
        label: "List messages",
        capabilityId: "gmail.messages.read",
        description:
          "Search and list Gmail messages using Gmail query syntax (e.g. from:someone, is:unread, subject:keyword). Returns up to 10 messages by default with full headers and body.",
        mutates: false,
        requiresConfirmation: false,
        arguments: [
          {
            name: "query",
            type: "string",
            description:
              "Gmail search query (same syntax as Gmail search bar). Examples: 'from:user@example.com', 'is:unread', 'subject:invoice after:2026/01/01'.",
            required: false,
          },
          {
            name: "labelIds",
            type: "string[]",
            description: "Filter by label IDs (e.g. INBOX, SENT, STARRED).",
            required: false,
          },
          {
            name: "maxResults",
            type: "number",
            description: "Maximum number of messages to return. Defaults to 10.",
            required: false,
          },
          {
            name: "pageToken",
            type: "string",
            description: "Pagination token from a previous list-messages response.",
            required: false,
          },
        ],
      },
      {
        id: "get-message",
        label: "Get message",
        capabilityId: "gmail.messages.read",
        description: "Fetch a single email with full headers, body, and metadata.",
        mutates: false,
        requiresConfirmation: false,
        arguments: [
          { name: "messageId", type: "string", description: "Gmail message identifier.", required: true },
        ],
      },
      {
        id: "send-message",
        label: "Send message",
        capabilityId: "gmail.messages.write",
        description: "Send a new email to one or more recipients.",
        mutates: true,
        requiresConfirmation: false,
        arguments: [
          {
            name: "to",
            type: "string",
            description: "Recipient email address(es), comma-separated.",
            required: true,
          },
          { name: "subject", type: "string", description: "Email subject line.", required: true },
          { name: "body", type: "string", description: "Plain text email body.", required: true },
          { name: "cc", type: "string", description: "CC recipients, comma-separated.", required: false },
          { name: "bcc", type: "string", description: "BCC recipients, comma-separated.", required: false },
        ],
      },
      {
        id: "reply-message",
        label: "Reply to message",
        capabilityId: "gmail.messages.write",
        description:
          "Reply to an existing email thread. Automatically sets In-Reply-To, References, and threadId for correct threading.",
        mutates: true,
        requiresConfirmation: false,
        arguments: [
          { name: "messageId", type: "string", description: "ID of the message to reply to.", required: true },
          { name: "body", type: "string", description: "Plain text reply body.", required: true },
          {
            name: "to",
            type: "string",
            description: "Override reply recipient (defaults to original sender).",
            required: false,
          },
          { name: "cc", type: "string", description: "CC recipients, comma-separated.", required: false },
        ],
      },
      {
        id: "forward-message",
        label: "Forward message",
        capabilityId: "gmail.messages.write",
        description: "Forward an existing email to a new recipient, including original message content.",
        mutates: true,
        requiresConfirmation: false,
        arguments: [
          { name: "messageId", type: "string", description: "ID of the message to forward.", required: true },
          { name: "to", type: "string", description: "Forward recipient email address(es).", required: true },
          {
            name: "body",
            type: "string",
            description: "Optional message to prepend before the forwarded content.",
            required: false,
          },
          { name: "cc", type: "string", description: "CC recipients, comma-separated.", required: false },
        ],
      },
      {
        id: "modify-labels",
        label: "Modify labels",
        capabilityId: "gmail.messages.manage",
        description:
          "Add or remove labels on a message. Use to mark read (remove UNREAD), star (add STARRED), archive (remove INBOX), etc.",
        mutates: true,
        requiresConfirmation: false,
        arguments: [
          { name: "messageId", type: "string", description: "Gmail message identifier.", required: true },
          {
            name: "addLabelIds",
            type: "string[]",
            description: "Label IDs to add (e.g. STARRED, IMPORTANT).",
            required: false,
          },
          {
            name: "removeLabelIds",
            type: "string[]",
            description: "Label IDs to remove (e.g. UNREAD, INBOX).",
            required: false,
          },
        ],
      },
      {
        id: "trash-message",
        label: "Trash message",
        capabilityId: "gmail.messages.manage",
        description: "Move a message to the trash. This is reversible from the Gmail UI within 30 days.",
        mutates: true,
        requiresConfirmation: true,
        arguments: [
          { name: "messageId", type: "string", description: "Gmail message identifier to trash.", required: true },
        ],
      },
      {
        id: "list-drafts",
        label: "List drafts",
        capabilityId: "gmail.drafts",
        description: "List email drafts with message summaries.",
        mutates: false,
        requiresConfirmation: false,
        arguments: [
          {
            name: "maxResults",
            type: "number",
            description: "Maximum number of drafts to return. Defaults to 10.",
            required: false,
          },
        ],
      },
      {
        id: "create-draft",
        label: "Create draft",
        capabilityId: "gmail.drafts",
        description: "Create a new email draft that can be sent later from Gmail.",
        mutates: true,
        requiresConfirmation: false,
        arguments: [
          {
            name: "to",
            type: "string",
            description: "Recipient email address(es), comma-separated.",
            required: true,
          },
          { name: "subject", type: "string", description: "Email subject line.", required: true },
          { name: "body", type: "string", description: "Plain text email body.", required: true },
          { name: "cc", type: "string", description: "CC recipients, comma-separated.", required: false },
          { name: "bcc", type: "string", description: "BCC recipients, comma-separated.", required: false },
        ],
      },
    ],
  },
}
