#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SUDOERS_TARGET="/etc/sudoers.d/opencode-restart"
SUDO_USER_NAME="${OPENCODE_RESTART_SUDO_USER:-$(id -un)}"

need_cmd() {
  local name="$1"
  local path
  path="$(command -v "${name}" 2>/dev/null || true)"
  if [ -z "${path}" ]; then
    printf 'Missing required command: %s\n' "${name}" >&2
    exit 1
  fi
  printf '%s' "${path}"
}

SUDO_BIN="$(need_cmd sudo)"
VISUDO_BIN="$(need_cmd visudo)"
MKDIR_BIN="$(need_cmd mkdir)"
RSYNC_BIN="$(need_cmd rsync)"
INSTALL_BIN="$(need_cmd install)"
SYSTEMCTL_BIN="$(need_cmd systemctl)"

FRONTEND_SOURCE="${REPO_ROOT}/packages/app/dist"
WEBCTL_SOURCE="${REPO_ROOT}/webctl.sh"
GATEWAY_SOURCE="${REPO_ROOT}/daemon/opencode-gateway"

if [ ! -d "${REPO_ROOT}/packages/app" ] || [ ! -f "${WEBCTL_SOURCE}" ]; then
  printf 'This script must run from an opencode source checkout. Resolved repo: %s\n' "${REPO_ROOT}" >&2
  exit 1
fi

if [ ! -f "${GATEWAY_SOURCE}" ]; then
  printf 'Gateway binary missing: %s\n' "${GATEWAY_SOURCE}" >&2
  printf 'Build it first if you need gateway self-update privileges.\n' >&2
  exit 1
fi

"${SUDO_BIN}" -v

tmpfile="$(mktemp)"
cleanup() {
  rm -f "${tmpfile}"
}
trap cleanup EXIT

cat > "${tmpfile}" <<EOF
# opencode controlled self-restart privileges
# Generated by ${REPO_ROOT}/scripts/install-opencode-restart-sudoers.sh
# Scope is intentionally narrow: fixed frontend sync, fixed binary installs, fixed gateway service restart.
Cmnd_Alias OPENCODE_RESTART_FRONTEND = ${MKDIR_BIN} -p /usr/local/share/opencode/frontend, ${RSYNC_BIN} -a --delete ${FRONTEND_SOURCE}/ /usr/local/share/opencode/frontend/
Cmnd_Alias OPENCODE_RESTART_INSTALL = ${INSTALL_BIN} -m 0755 ${WEBCTL_SOURCE} /etc/opencode/webctl.sh, ${INSTALL_BIN} -m 0755 ${GATEWAY_SOURCE} /usr/local/bin/opencode-gateway
Cmnd_Alias OPENCODE_RESTART_SERVICE = ${SYSTEMCTL_BIN} restart opencode-gateway.service
${SUDO_USER_NAME} ALL=(root) NOPASSWD: OPENCODE_RESTART_FRONTEND, OPENCODE_RESTART_INSTALL, OPENCODE_RESTART_SERVICE
EOF

"${SUDO_BIN}" "${VISUDO_BIN}" -c -f "${tmpfile}"

if "${SUDO_BIN}" test -f "${SUDOERS_TARGET}"; then
  backup="${SUDOERS_TARGET}.bak.$(date +%Y%m%d%H%M%S)"
  "${SUDO_BIN}" cp "${SUDOERS_TARGET}" "${backup}"
  printf 'Backed up existing sudoers file: %s\n' "${backup}"
fi

"${SUDO_BIN}" "${INSTALL_BIN}" -m 0440 "${tmpfile}" "${SUDOERS_TARGET}"
"${SUDO_BIN}" "${VISUDO_BIN}" -c -f /etc/sudoers
"${SUDO_BIN}" "${VISUDO_BIN}" -c -f "${SUDOERS_TARGET}"

printf 'Installed opencode restart sudoers allowlist: %s\n' "${SUDOERS_TARGET}"
printf 'Granted user: %s\n' "${SUDO_USER_NAME}"
